### ISSUE TITLE
Extra tab after column headers in datanodes.tsv

### ISSUE THREAD

**Issue by larsgw** [wikipathways/wikipathways-database#1]
The `WP*-datanodes.tsv` files have an extra tab after the column headers. GitHub complains about this in [the file viewer](https://github.com/wikipathways/wikipathways-database/blob/main/pathways/WP1/WP1-datanodes.tsv), and other parsers might struggle too.

**Comment by mkutmon** [comment]
I think that is solved. Can you confirm?

**Comment by larsgw** [comment]
I think so, yes.
