### ISSUE TITLE
index.js runs on all ~1800 WPIDs every time one is updates

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways-database#14]
All the other steps take a list of WPIDs as an argument to efficiently process only the GPML that is changed. Ideally, index.js could also accept this arg and only bother generating bibliography.tsv files for just those that have changed.

Mainly an efficiency issue; not really a bug.

**Comment by larsgw** [comment]
One counterpoint would be that reading the other files helps build the cache of references. So if a newly introduced reference is a Pubmed ID that is already referenced in another pathway, it does not have to fetch from the API again. (Note that the script does not call the Pubmed API for all 1800 WPIDs every time, only for new Pubmed IDs.)

**Comment by AlexanderPico** [comment]
Ah, I see. It goes through all WPIDs and builds a cache from previously collected refs and then checks all GPMLs for any new refs and calls Pubmed API for those. Interesting.

I don't have data to back up my intuition, but I wouldn't expect much redundancy. But I could be wrong.

Overall, still seems less efficient than just dealing with the one (or few) GPMLs in a given push. But probably not a "big fish," so I'll go ahead and close this one. Thanks for clarifying!
