### ISSUE TITLE
index.js drops all non-pubmed references from bibliography

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways-database#15]
Currently, only `Pubmed` entries are processed and written to bibliography.tsv. Is there a plan to process (or pass along) the non-Pubmed references?

For example, WP5303 has 3 references which can be seen on the "classic" site:
https://www.wikipathways.org/index.php/Pathway:WP5303

But, the new site only shows the 2 Pubmed entries:
https://new.wikipathways.org/pathways/WP5303.html

**Comment by larsgw** [comment]
The third source is entered like this in the GPML:

```xml
    <bp:PublicationXref xmlns:bp="http://www.biopax.org/release/biopax-level3.owl#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf:id="d66">
      <bp:ID rdf:datatype="http://www.w3.org/2001/XMLSchema#string"></bp:ID>
      <bp:DB rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PubMed</bp:DB>
      <bp:TITLE rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Handbook of Glycosyltransferases  and Related Genes</bp:TITLE>
      <bp:SOURCE rdf:datatype="http://www.w3.org/2001/XMLSchema#string">https://doi.org/10.1007/978-4-431-67877-9</bp:SOURCE>
      <bp:YEAR rdf:datatype="http://www.w3.org/2001/XMLSchema#string">2002</bp:YEAR>
    </bp:PublicationXref>
```

The `WP5303-refs.tsv` looks like this:

|ID|Database|
|---|---|
|15938018|Pubmed|
|NA|NA|
|7890749|Pubmed|

So this would first need to be fixed in both the GPML and the script that generates `WP5303-refs.tsv`. Then, to add support to the `generate-references/` script would be pretty simple.

**Comment by larsgw** [comment]
I have added support for DOIs and ISBNs in #17. I have also gone through all the pathways for which `generate-references` reports errors and added PubMed, DOI, or ISBN identifiers where possible. Some websites and theses do not have standard references, we need to figure out how to handle those.

**Comment by AlexanderPico** [comment]
Looks great! Huge improvement to the ref sections on the new site.
