### ISSUE TITLE
Pubmed API rate limit

### ISSUE THREAD

**Issue by larsgw** [wikipathways/wikipathways-database#19]
Since this action was made the Pubmed API has introduced a rate limit of 3 requests per second. This is fine needs to be handled in Citation.js (see https://github.com/citation-js/plugin-pubmed/issues/2).

**Comment by AlexanderPico** [comment]
Our citedin_lookup.R script already has a built-in delay per query (https://github.com/wikipathways/wikipathways-database/blob/main/scripts/citedin_lookup.R#L62), so it's fixed.

But our index.js script does not. However, @larsgw filed an issue with Citation.js (above), so we are expecting them to fix it and then we'll pull in the newer version when it's ready (https://github.com/wikipathways/wikipathways-database/blob/main/scripts/generate-references/index.js#L6). Is that the plan?  

Will index.js work in the meantime? It seems to be. Why is it working?

**Comment by larsgw** [comment]
It's working because it's not fetching the data of every PubMed identifier every time, it only fetches the data of new PubMed identifiers.

As a sidenote, I am the maintainer of Citation.js, I'm still deciding how best to fix this.
