### ISSUE TITLE
Re-enable copying of thumbnails in manual sync GitHub Action

### ISSUE THREAD

**Issue by larsgw** [wikipathways/wikipathways-database#23]
When the issue with missing thumbnails (e.g. WP1010) is fixed, the copying of thumbnails in the `manual_jekyll_sync.yml` action should be added again. See [5e7f0e1](https://github.com/wikipathways/wikipathways-database/commit/5e7f0e1e2630ccd40de00054dd89c9508372d799)

**Comment by AlexanderPico** [comment]
done
