### ISSUE TITLE
Bridgedb and Ovis aries

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways-database#25]
This pathway broke our latest sync attempt: https://classic.wikipathways.org/index.php/Pathway:WP5196

The error was in the webservice call to BridgeDb:

`https://webservice.bridgedb.org/Ovis aries/xrefsBatch`

And I don't see Ovis aries in the support list of organisms.

Plan to add it or should this pathway be flagged as not acceptable?

**Comment by egonw** [comment]
Mmm... weird. Yeah, BridgeDb supports it. But when I check https://webservice.bridgedb.org/Ovis%20aries/properties or https://webservice.bridgedb.org/Sheep/properties I indeed not get results.

**Comment by egonw** [comment]
I see sheep in our actions, line 80 and 100:

- https://github.com/wikipathways/wikipathways-database/blob/main/.github/workflows/scheduled_bridge_cache.yml#L80
- https://github.com/wikipathways/wikipathways-database/blob/main/.github/workflows/scheduled_bridge_cache.yml#L100

At the same time, I think I can confirm that our BridgeDb WS is not hosting it: https://webservice.bridgedb.org/Ovis%20aries/properties

**Comment by egonw** [comment]
Okay, the problem is that I am not running the latest BridgeDb on the webservices, but the older 3.0.13. I'll fix this this week.

**Comment by egonw** [comment]
![image](https://user-images.githubusercontent.com/26721/220198817-fdc303c3-452b-4e1a-a165-6d56a80c6cc0.png)

I think we're back in business.

**Comment by AlexanderPico** [comment]
Thanks! I'll mark the pathway as approved (again) and see if it run through our pipeline to the new site.

**Comment by AlexanderPico** [comment]
Done!
