### ISSUE TITLE
Newline characters in the comments result in TSVs that break jekyll

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways-database#26]
https://classic.wikipathways.org/index.php/Pathway:WP5235

This pathway includes datanode comments with newline characters. The resulting TSV cannot be read by Jekyll without quotes surrounding the field.

Perhaps meta-data-action can add quotes around all comment fields to catch cases like this?

**Comment by egonw** [comment]
Fixed!
