### ISSUE TITLE
explore Zenodo action for monthly archive of GPML files

### ISSUE THREAD

**Issue by egonw** [wikipathways/wikipathways-database#27]
See https://github.com/marketplace/actions/zenodo-publish

(HT ELIXIR Data Platform, H. Rasche)

**Comment by hexylena** [comment]
It's an interesting use case, I look forward to what you come up with! It could potentially be useful to me as well, since in some cases we want zenodo IDs, but not for the whole repository.

**Comment by AlexanderPico** [comment]
https://github.com/wikipathways/wikipathways-data-release/blob/main/.github/workflows/publish_latest_to_zenodo.yml
