### ISSUE TITLE
duplicates in the Participant table

### ISSUE THREAD

**Issue by egonw** [wikipathways/wikipathways-database#42]
E.g. in https://www.wikipathways.org/pathways/WP5336:

![image](https://github.com/wikipathways/wikipathways-database/assets/26721/43f9aa1d-b17b-4f17-8b38-ab18bdc5824a)

**Comment by khanspers** [comment]
This was discussed in another [issue](https://github.com/wikipathways/wikipathways.github.io/issues/32) and we decided keeping all instances of participants from the pathway in the table is preferred. Closing.

**Comment by egonw** [comment]
Ah, that makes sense. The label can be different, etc.
