### ISSUE TITLE
Wpblocked should not be shown

### ISSUE THREAD

**Issue by egonw** [wikipathways/wikipathways-database#45]
Currently, on the [Recently Updated Pathways](https://www.wikipathways.org/browse/updated.html) some author names are now shown:

![image](https://github.com/wikipathways/wikipathways-database/assets/26721/0fa42840-0103-49db-b9e3-0a3c45d6f646)

One (in the above screenshot right after Freddie) is likely intentional: `<a href="https://wikipathways.org/authors/Wpblocked.html" title="View author profile"></a>`

It would be nice if that would be filtered out during the page creation.

**Comment by khanspers** [comment]
I think this was fixed by https://github.com/wikipathways/wikipathways.github.io/commit/5cfab336dfa2df22c063de80eb5651ceac965a87. Closing for now.
