### ISSUE TITLE
Possible issues with references

### ISSUE THREAD

**Issue by larsgw** [wikipathways/wikipathways-database#51]
|Pathway|Database|ID|Reason|Fixed|
|---|---|---|---|---|
|WP3933|Pubmed|`33093177`|PubMed: "PMID: 33093177 was deleted because it is a duplicate of PMID: 33454021"|✅|
|WP4220|Pubmed|`9783642403361`|ISBN|✅|
|WP490|Pubmed|`0415299004`|ISBN-10?|✅|
|WP5074|Pubmed|`R-HSA-5654346.1`|Reactome|✅ (sync issue)|
|WP5178|Pubmed|`10.1007/978-3-642-40337-8`|DOI(+ISBN)|✅|
|WP5277|Pubmed|`21255593.`|Punctuation|✅|
|WP5316|Pubmed|`36099812;`|Punctuation|✅|
|WP5322|Pubmed|`34470047.`|Punctuation|✅|
|WP5356|Pubmed|`31108916.`|Punctuation|✅|
|WP5381|Pubmed|`23177736,`|Punctuation (also duplicates)|✅|
|WP5381|Pubmed|`:26711011`|Punctuation (also duplicates)|✅|
|WP5401|Pubmed|`15778465.`|Punctuation|✅|
|WP5420|DOI|`10.4137/IJTR.S8`|`158` cut off (also duplicates)|✅|
|WP5420|DOI|`10.1186s40246-021-00319-2`|No slash|✅|
|WP5420|DOI|`10.1016/j.jphs.2022.08.00`|Cut off, no easy fix||
|WP5420|DOI|`10.1161/01.ATV.0000243924.00970`|`.cb` cut off|✅|
|WP5420|DOI|`10.1016/j.humgen.2022.20109`|Ending cut off, probably [10.1016/j.humgen.2022.201096](https://doi.org/10.1016/j.humgen.2022.201096)|✅|
|WP5420|DOI|`10.15586/codonpublications.parkinsonsdisease.2018.ch`|Cut off, no easy fix||
|WP5420|DOI|`10.3390nu8020068`|No slash|✅|
|WP5420|DOI|`10.4137/IJTR.S815810.4137/IJTR.S8158`|DOI repeated (also duplicates)|✅|

Also a number of references with empty rows.

**Comment by larsgw** [comment]
Not all of these are easily fixable, as there are often multiple articles that fit in the pattern and no other information is given. E.g. `10.15586/codonpublications.parkinsonsdisease.2018.ch` could be any of multiple chapters.

**Comment by egonw** [comment]
@larsgw, I suggest we close this issue. The remaining two open items can be left via "Discuss this pathway" on the new website, https://www.wikipathways.org/pathways/WP5420

**Comment by larsgw** [comment]
:+1: https://github.com/wikipathways/wikipathways-help/discussions/89
