### ISSUE TITLE
Maintain global file of formatted (PubMed) references?

### ISSUE THREAD

**Issue by larsgw** [wikipathways/wikipathways-database#7]
Instead of, or in addition to, writing the formatted references to TSV files specific to each pathway, it may be more efficient to write all references to a global JSON file. This would make it easier to read it for caching, and de-duplicate the file contents.

**Comment by AlexanderPico** [comment]
But now that we've done the bulk work, we only need `index.js` to run on one or a few GPMLs at a time. The greater efficiency would be for the js script to take the list of changed WPIDs as an arg and only processes the references in those GPMLs. See variable ${{needs.changed-gpmls.outputs.added-modified}} in the GH Actions.

**Comment by egonw** [comment]
@larsgw, this is the current implementation, right?

**Comment by larsgw** [comment]
No, but I don't think it would be a big performance difference compared to other parts of the workflow.
